import type { ScreenTemplate, FreeLayoutTemplate } from "@/types/template";

/**
 * 预设大屏模板配置
 * 包含各种常用的大屏布局模板
 */

// 0. 空模板（自由布局）
export const emptyFreeTemplate: FreeLayoutTemplate = {
  id: "empty-free",
  name: "空模板（自由布局）",
  description: "完全自由的画布，支持自由拖拽和定位组件",
  category: "basic",
  layoutMode: "free",
  canvasWidth: '100%',
  canvasHeight: '100%',
  areas: [], // 初始为空，用户拖拽时动态创建区域
  backgroundColor: "#081324",
};

// 1. 基础网格布局 - 适合通用场景
export const basicGridTemplate: ScreenTemplate = {
  id: "basic-grid",
  name: "基础网格布局",
  description: "经典的网格布局，适合各类数据展示场景",
  category: "basic",
  layoutMode: "grid",
  gridRows: 12,
  gridCols: 24,
  areas: [
    {
      id: "header",
      name: "顶部标题区",
      x: 0,
      y: 0,
      w: 24,
      h: 2,
      description: "大屏标题、时间等信息",
    },
    {
      id: "left-top",
      name: "左上区域",
      x: 0,
      y: 2,
      w: 8,
      h: 5,
      description: "图表或数据卡片",
    },
    {
      id: "left-bottom",
      name: "左下区域",
      x: 0,
      y: 7,
      w: 8,
      h: 5,
      description: "图表或数据卡片",
    },
    {
      id: "center",
      name: "中央区域",
      x: 8,
      y: 2,
      w: 8,
      h: 10,
      description: "主要展示区域",
    },
    {
      id: "right-top",
      name: "右上区域",
      x: 16,
      y: 2,
      w: 8,
      h: 5,
      description: "图表或数据卡片",
    },
    {
      id: "right-bottom",
      name: "右下区域",
      x: 16,
      y: 7,
      w: 8,
      h: 5,
      description: "图表或数据卡片",
    },
  ],
  backgroundColor: "#081324",
};

// 2. 经典三栏布局
export const threeColumnTemplate: ScreenTemplate = {
  id: "three-column",
  name: "经典三栏布局",
  description: "左中右三栏结构，适合数据监控和仪表盘",
  category: "dashboard",
  layoutMode: "grid",
  gridRows: 12,
  gridCols: 24,
  areas: [
    {
      id: "header",
      name: "顶部标题区",
      x: 0,
      y: 0,
      w: 24,
      h: 2,
      description: "页面标题和状态信息",
    },
    {
      id: "left-column",
      name: "左侧列",
      x: 0,
      y: 2,
      w: 6,
      h: 10,
      description: "侧边栏数据展示",
    },
    {
      id: "center-column",
      name: "中央列",
      x: 6,
      y: 2,
      w: 12,
      h: 10,
      description: "核心数据展示区",
    },
    {
      id: "right-column",
      name: "右侧列",
      x: 18,
      y: 2,
      w: 6,
      h: 10,
      description: "辅助信息展示",
    },
  ],
  backgroundColor: "#081324",
};

// 3. KPI仪表盘布局
export const kpiDashboardTemplate: ScreenTemplate = {
  id: "kpi-dashboard",
  name: "KPI仪表盘",
  description: "突出关键指标展示，适合管理驾驶舱",
  category: "dashboard",
  layoutMode: "grid",
  gridRows: 12,
  gridCols: 24,
  areas: [
    {
      id: "title",
      name: "标题区",
      x: 0,
      y: 0,
      w: 24,
      h: 2,
      description: "仪表盘标题",
    },
    {
      id: "kpi-1",
      name: "KPI指标1",
      x: 0,
      y: 2,
      w: 6,
      h: 3,
      description: "关键指标卡片",
    },
    {
      id: "kpi-2",
      name: "KPI指标2",
      x: 6,
      y: 2,
      w: 6,
      h: 3,
      description: "关键指标卡片",
    },
    {
      id: "kpi-3",
      name: "KPI指标3",
      x: 12,
      y: 2,
      w: 6,
      h: 3,
      description: "关键指标卡片",
    },
    {
      id: "kpi-4",
      name: "KPI指标4",
      x: 18,
      y: 2,
      w: 6,
      h: 3,
      description: "关键指标卡片",
    },
    {
      id: "chart-main",
      name: "主图表区",
      x: 0,
      y: 5,
      w: 16,
      h: 7,
      description: "主要数据图表",
    },
    {
      id: "chart-side",
      name: "侧边图表",
      x: 16,
      y: 5,
      w: 8,
      h: 7,
      description: "辅助数据图表",
    },
  ],
  backgroundColor: "#081324",
};

// 4. 数据监控大屏
export const monitorTemplate: ScreenTemplate = {
  id: "data-monitor",
  name: "数据监控大屏",
  description: "实时监控场景，突出中心主图",
  category: "monitor",
  layoutMode: "grid",
  gridRows: 12,
  gridCols: 24,
  areas: [
    {
      id: "header",
      name: "顶栏",
      x: 0,
      y: 0,
      w: 24,
      h: 2,
      description: "标题和实时状态",
    },
    {
      id: "left-top",
      name: "左上卡片",
      x: 0,
      y: 2,
      w: 6,
      h: 3,
      description: "数据卡片",
    },
    {
      id: "left-middle",
      name: "左中卡片",
      x: 0,
      y: 5,
      w: 6,
      h: 4,
      description: "数据卡片",
    },
    {
      id: "left-bottom",
      name: "左下卡片",
      x: 0,
      y: 9,
      w: 6,
      h: 3,
      description: "数据卡片",
    },
    {
      id: "center-main",
      name: "中央主图",
      x: 6,
      y: 2,
      w: 12,
      h: 10,
      description: "核心展示区域（地图/大图表）",
    },
    {
      id: "right-top",
      name: "右上卡片",
      x: 18,
      y: 2,
      w: 6,
      h: 3,
      description: "数据卡片",
    },
    {
      id: "right-middle",
      name: "右中卡片",
      x: 18,
      y: 5,
      w: 6,
      h: 4,
      description: "数据卡片",
    },
    {
      id: "right-bottom",
      name: "右下卡片",
      x: 18,
      y: 9,
      w: 6,
      h: 3,
      description: "数据卡片",
    },
  ],
  backgroundColor: "#081324",
};

// 5. 全屏地图布局
export const fullMapTemplate: ScreenTemplate = {
  id: "full-map",
  name: "全屏地图布局",
  description: "以地图为主的布局，适合地理数据展示",
  category: "monitor",
  layoutMode: "grid",
  gridRows: 12,
  gridCols: 24,
  areas: [
    {
      id: "header",
      name: "顶部标题",
      x: 6,
      y: 0,
      w: 12,
      h: 2,
      description: "页面标题（透明覆盖）",
    },
    {
      id: "map-main",
      name: "地图主区",
      x: 4,
      y: 2,
      w: 16,
      h: 10,
      description: "地图展示区域",
    },
    {
      id: "left-panel",
      name: "左侧面板",
      x: 0,
      y: 2,
      w: 4,
      h: 10,
      description: "数据列表或筛选",
    },
    {
      id: "right-panel",
      name: "右侧面板",
      x: 20,
      y: 2,
      w: 4,
      h: 10,
      description: "统计信息",
    },
  ],
  backgroundColor: "#081324",
};

// 6. 数据分析四宫格
export const fourQuadrantTemplate: ScreenTemplate = {
  id: "four-quadrant",
  name: "四宫格分析",
  description: "四象限布局，适合对比分析",
  category: "data-analysis",
  layoutMode: "grid",
  gridRows: 12,
  gridCols: 24,
  areas: [
    {
      id: "header",
      name: "顶部标题",
      x: 0,
      y: 0,
      w: 24,
      h: 2,
      description: "分析主题",
    },
    {
      id: "quadrant-1",
      name: "象限一",
      x: 0,
      y: 2,
      w: 12,
      h: 5,
      description: "数据分析区域",
    },
    {
      id: "quadrant-2",
      name: "象限二",
      x: 12,
      y: 2,
      w: 12,
      h: 5,
      description: "数据分析区域",
    },
    {
      id: "quadrant-3",
      name: "象限三",
      x: 0,
      y: 7,
      w: 12,
      h: 5,
      description: "数据分析区域",
    },
    {
      id: "quadrant-4",
      name: "象限四",
      x: 12,
      y: 7,
      w: 12,
      h: 5,
      description: "数据分析区域",
    },
  ],
  backgroundColor: "#081324",
};

// 7. 瀑布流布局
export const waterfallTemplate: ScreenTemplate = {
  id: "waterfall",
  name: "瀑布流布局",
  description: "不规则网格布局，适合多种尺寸组件混排",
  category: "custom",
  layoutMode: "grid",
  gridRows: 12,
  gridCols: 24,
  areas: [
    {
      id: "header",
      name: "标题区",
      x: 0,
      y: 0,
      w: 24,
      h: 2,
    },
    {
      id: "block-1",
      name: "区块1",
      x: 0,
      y: 2,
      w: 8,
      h: 4,
    },
    {
      id: "block-2",
      name: "区块2",
      x: 8,
      y: 2,
      w: 8,
      h: 6,
    },
    {
      id: "block-3",
      name: "区块3",
      x: 16,
      y: 2,
      w: 8,
      h: 5,
    },
    {
      id: "block-4",
      name: "区块4",
      x: 0,
      y: 6,
      w: 8,
      h: 6,
    },
    {
      id: "block-5",
      name: "区块5",
      x: 16,
      y: 7,
      w: 8,
      h: 5,
    },
    {
      id: "block-6",
      name: "区块6",
      x: 8,
      y: 8,
      w: 8,
      h: 4,
    },
  ],
  backgroundColor: "#081324",
};

// 导出所有模板（包括自由布局和网格布局）
export const allTemplates: (ScreenTemplate | FreeLayoutTemplate)[] = [
  emptyFreeTemplate,
  basicGridTemplate,
  threeColumnTemplate,
  kpiDashboardTemplate,
  monitorTemplate,
  fullMapTemplate,
  fourQuadrantTemplate,
  waterfallTemplate,
];

// 按分类导出模板
export const templatesByCategory = {
  basic: [emptyFreeTemplate, basicGridTemplate],
  dashboard: [threeColumnTemplate, kpiDashboardTemplate],
  monitor: [monitorTemplate, fullMapTemplate],
  "data-analysis": [fourQuadrantTemplate],
  custom: [waterfallTemplate],
};


